name: Lint Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.9"
      - name: Install SQLFluff
        run: "pip install sqlfluff==3.1.0"
      - name: Lint models
        run: "sqlfluff lint ./dbt/models/ --dialect ansi --ignore=templating"

